### ISSUE TITLE
Just an idea

### ISSUE THREAD

**Issue by Bowarc** [Vixeliz/ggez_atlas#1]
Shouldn't `TextureAtlas.textures`'s key be an user made type that impl `Hash` so the user could make it's own `TextureId` enum and index the atlas with it?

I know it's not finished yet, just wondering if that would be a good idea and if not, why.

Looks rly cool tho

**Comment by Muvkina** [comment]
Good idea i'll be honest I just threw this together cause it was something needed for my voxel project. But yeah i'll make this change thanks for the suggestion.
